### ISSUE TITLE
rlp encodes 0 to 00

### ISSUE THREAD

**Issue by asinyagin** [wanderer/rlp#3]
Hey,

Here's a problems with encoding of `0`:
```
console.log(rlp.encode(0).toString('hex'));
```
prints `00` but should print `80`.

Because of that ethereumjs-vm generates wrong new address if contract was created from an account with nonce 0.

**Comment by wanderer** [comment]
@asinyagin  console.log(rlp.encode().toString('hex')); give 80

**Comment by asinyagin** [comment]
Yeah, probably I'm missing something, but with rlp 1.0.1 it works correctly.

Also, `console.log(util.generateAddress(new Buffer('62a496c75751c67e600f5d04e763b85d4069af8e', 'hex'), new Buffer('01', 'hex')).toString('hex'));` gives `3570b5c5329c01b54d9e94e4547e7d465229b807`, but should give `ad1a41f7e5ff04f81c2e7b73c026254fa73851e4`, if I'm not mistaken.

**Comment by asinyagin** [comment]
```javascript
console.log(util.generateAddress(new Buffer('62a496c75751c67e600f5d04e763b85d4069af8e', 'hex'), new Buffer('02', 'hex')).toString('hex'));
```
gives the correct address `750bcaba91b332de719619d51abeec8bf5e9d9b2`

**Comment by wanderer** [comment]
oh yes thanks @asinyagin this is a problem. Ill try to get it figured out today

**Comment by wanderer** [comment]
generateAddress changed here ethereumjs-util/issues/4

**Comment by wanderer** [comment]
zero encoding fix in 1.1.2 @asinyagin thanks for catching this!

**Comment by asinyagin** [comment]
@wanderer thank you

**Comment by asinyagin** [comment]
i'm still getting `3570b5c5329c01b54d9e94e4547e7d465229b807` from
```javascript
console.log(util.generateAddress(new Buffer('62a496c75751c67e600f5d04e763b85d4069af8e', 'hex'), new Buffer('01', 'hex')).toString('hex'));
```
with rlp 1.1.2. It should be `ad1a41f7e5ff04f81c2e7b73c026254fa73851e4`. is that another error?

**Comment by wanderer** [comment]
@asinyagin really really sorry for the confusin. what you want is 
util.generateAddress(new Buffer('62a496c75751c67e600f5d04e763b85d4069af8e', 'hex'), 0).toString('hex')

We changed to count from zero

**Comment by asinyagin** [comment]
@asinyagin ok, thanks
